[build-system]
requires = [
    'setuptools ~= 80.0',
]
build-backend = 'setuptools.build_meta'

[project]
name = 'ancestry'
version = '0.0.0'
authors = [
  {name = 'Bart Feenstra', email = 'bar@bartfeenstra.com'},
]
requires-python = '~= 3.13'
dependencies = [
    'betty ~= 0.5.0a37',
    'betty-nginx ~= 0.2.0a13',
]

[project.entry-points.'betty.command']
'report' = 'ancestry.plugins.command.report:Report'

[project.entry-points.'betty.enricher']
'ancestry' = 'ancestry.plugins.enricher.ancestry:Ancestry'

[project.entry-points.'betty.link']
'about-the-author' = 'ancestry.plugins.link.about_the_author:ABOUT_THE_AUTHOR'

[project.optional-dependencies]
development = [
    'aioresponses ~= 0.7.8',
    'pytest ~= 9.0',
    'pytest-asyncio ~= 1.1',
    'ruff ~= 0.15.0',
    'ty == 0.0.32',
]

[tool.setuptools.packages.find]
where = ['.']

[tool.setuptools.package-data]
betty = [
    'py.typed',
    'assets/**',
]

[tool.setuptools.exclude-package-data]
betty = [
    '__pycache__',
]
