name: Test

on:
  schedule:
    - cron: '24 * * * *'
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: 'Python 3.13'
            os: ubuntu-latest
            python: '3.13'
          - name: 'Python 3.12'
            os: ubuntu-latest
            python: '3.12'
    timeout-minutes: 60
    steps:
      - name: Check out the source code
        uses: actions/checkout@v5

      - name: Get the pip cache directory
        run: echo "pip_cache_dir=$(pip cache dir)" >> $GITHUB_ENV
        shell: bash

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ env.pip_cache_dir }}
          key: pip-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('./setup.py') }}
          restore-keys: |
            pip-${{ runner.os }}-${{ matrix.python }}-

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Build the development environment
        run: |
          ./bin/build-dev
        shell: bash

      - name: Run the tests
        run: |
          ./bin/test
        shell: bash
